/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['Inter', 'system-ui', 'sans-serif'],
      },
      fontSize: {
        'xs': ['calc(var(--font-size-base, 14px) * 0.75)', { lineHeight: '1rem' }],
        'sm': ['calc(var(--font-size-base, 14px) * 0.875)', { lineHeight: '1.25rem' }],
        'base': ['var(--font-size-base, 14px)', { lineHeight: '1.5rem' }],
        'lg': ['calc(var(--font-size-base, 14px) * 1.125)', { lineHeight: '1.75rem' }],
        'xl': ['calc(var(--font-size-base, 14px) * 1.25)', { lineHeight: '1.75rem' }],
        '2xl': ['calc(var(--font-size-base, 14px) * 1.5)', { lineHeight: '2rem' }],
        '3xl': ['calc(var(--font-size-base, 14px) * 1.875)', { lineHeight: '2.25rem' }],
        '4xl': ['calc(var(--font-size-base, 14px) * 2.25)', { lineHeight: '2.5rem' }],
        '5xl': ['calc(var(--font-size-base, 14px) * 3)', { lineHeight: '1' }],
        '6xl': ['calc(var(--font-size-base, 14px) * 3.75)', { lineHeight: '1' }],
        '7xl': ['calc(var(--font-size-base, 14px) * 4.5)', { lineHeight: '1' }],
        '8xl': ['calc(var(--font-size-base, 14px) * 6)', { lineHeight: '1' }],
        '9xl': ['calc(var(--font-size-base, 14px) * 8)', { lineHeight: '1' }],
      },
    },
  },
  plugins: [
    require('daisyui'),
    require('@tailwindcss/typography'),
  ],
  daisyui: {
    themes: [
      "light",
      "dark",
      "cupcake",
      "bumblebee",
      "emerald",
      "corporate",
      "synthwave",
      "retro",
      "cyberpunk",
      "valentine",
      "halloween",
      "garden",
      "forest",
      "aqua",
      "lofi",
      "pastel",
      "fantasy",
      "wireframe",
      "black",
      "luxury",
      "dracula",
      "cmyk",
      "autumn",
      "business",
      "acid",
      "lemonade",
      "night",
      "coffee",
      "winter",
      "dim",
      "nord",
      "sunset",
    ],
    darkTheme: "dark",
    base: true,
    styled: true,
    utils: true,
    prefix: "",
    logs: true,
    themeRoot: ":root",
  },
}