import type { IntruderBuiltInPayloadListDefinition } from './intruderBuiltInPayloadCatalogShared'

const COMMON_SUBDOMAINS = ['www', 'api', 'admin', 'app', 'dev', 'test', 'staging', 'static', 'cdn', 'm', 'wap', 'open']
const COMMON_PORTS = ['21', '22', '25', '53', '80', '110', '143', '443', '445', '3306', '3389', '5432', '6379', '8080', '8443']
const COMMON_API_ENDPOINTS = [
  '/api',
  '/api/v1',
  '/api/v2',
  '/auth',
  '/login',
  '/logout',
  '/user',
  '/users',
  '/admin',
  '/health',
  '/metrics',
  '/swagger',
  '/openapi.json',
]
const SENSITIVE_FILES = [
  '.env',
  '.git/config',
  '.git/HEAD',
  'config.json',
  'application.yml',
  'application.properties',
  'web.config',
  'phpinfo.php',
  'swagger.json',
  'openapi.json',
  'robots.txt',
  'backup.zip',
]

export const INTRUDER_DISCOVERY_PAYLOAD_LISTS: IntruderBuiltInPayloadListDefinition[] = [
  {
    id: 'subdomains-common',
    categoryKey: 'trafficAnalysis.intruder.builtInPayloadListCategories.discovery',
    labelKey: 'trafficAnalysis.intruder.builtInPayloadLists.commonSubdomains',
    descriptionKey: 'trafficAnalysis.intruder.builtInPayloadDescriptions.commonSubdomains',
    aliases: ['subdomain', 'dns', 'host', '子域名'],
    tags: ['discovery', 'subdomain'],
    recommendedAttackTypes: ['clusterBomb', 'pitchfork'],
    recommendedPositionHints: ['host', 'subdomain', 'domain'],
    items: COMMON_SUBDOMAINS,
  },
  {
    id: 'directories-short',
    categoryKey: 'trafficAnalysis.intruder.builtInPayloadListCategories.discovery',
    labelKey: 'trafficAnalysis.intruder.builtInPayloadLists.directoriesShort',
    descriptionKey: 'trafficAnalysis.intruder.builtInPayloadDescriptions.directoriesShort',
    aliases: ['directory', 'path', 'folder', '目录', '路径'],
    tags: ['discovery', 'directory'],
    recommendedAttackTypes: ['sniper', 'clusterBomb'],
    recommendedPositionHints: ['path', 'dir', 'directory', 'folder'],
    items: ['admin', 'api', 'backup', 'config', 'dev', 'files', 'private', 'test', 'uploads'],
  },
  {
    id: 'directories-long',
    categoryKey: 'trafficAnalysis.intruder.builtInPayloadListCategories.discovery',
    labelKey: 'trafficAnalysis.intruder.builtInPayloadLists.directoriesLong',
    descriptionKey: 'trafficAnalysis.intruder.builtInPayloadDescriptions.directoriesLong',
    aliases: ['directory', 'path', 'folder', 'long', '目录', '路径'],
    tags: ['discovery', 'directory'],
    recommendedAttackTypes: ['sniper', 'clusterBomb'],
    recommendedPositionHints: ['path', 'dir', 'directory', 'folder'],
    items: [
      'administrator',
      'app',
      'assets',
      'console',
      'dashboard',
      'internal',
      'management',
      'static',
      'uploads',
      'webdav',
      'wp-admin',
      'wp-content',
    ],
  },
  {
    id: 'filenames-short',
    categoryKey: 'trafficAnalysis.intruder.builtInPayloadListCategories.discovery',
    labelKey: 'trafficAnalysis.intruder.builtInPayloadLists.filenamesShort',
    descriptionKey: 'trafficAnalysis.intruder.builtInPayloadDescriptions.filenamesShort',
    aliases: ['filename', 'file', '文件名', '文件'],
    tags: ['discovery', 'filename'],
    recommendedAttackTypes: ['sniper', 'clusterBomb'],
    recommendedPositionHints: ['file', 'filename', 'name', 'resource'],
    items: ['index', 'login', 'admin', 'config', 'debug', 'status', 'test', 'backup'],
  },
  {
    id: 'filenames-long',
    categoryKey: 'trafficAnalysis.intruder.builtInPayloadListCategories.discovery',
    labelKey: 'trafficAnalysis.intruder.builtInPayloadLists.filenamesLong',
    descriptionKey: 'trafficAnalysis.intruder.builtInPayloadDescriptions.filenamesLong',
    aliases: ['filename', 'file', 'long', '文件名', '文件'],
    tags: ['discovery', 'filename'],
    recommendedAttackTypes: ['sniper', 'clusterBomb'],
    recommendedPositionHints: ['file', 'filename', 'name', 'resource'],
    items: [
      'application',
      'configuration',
      'credentials',
      'environment',
      'healthcheck',
      'phpinfo',
      'swagger',
      'web.config',
      '.env',
      '.gitignore',
    ],
  },
  {
    id: 'extensions-short',
    categoryKey: 'trafficAnalysis.intruder.builtInPayloadListCategories.discovery',
    labelKey: 'trafficAnalysis.intruder.builtInPayloadLists.extensionsShort',
    descriptionKey: 'trafficAnalysis.intruder.builtInPayloadDescriptions.extensionsShort',
    aliases: ['extension', 'suffix', 'ext', '扩展名'],
    tags: ['discovery', 'extension'],
    recommendedAttackTypes: ['clusterBomb', 'pitchfork'],
    recommendedPositionHints: ['ext', 'extension', 'suffix'],
    items: ['.bak', '.cfg', '.db', '.gz', '.ini', '.log', '.old', '.sql', '.txt', '.zip'],
  },
  {
    id: 'extensions-long',
    categoryKey: 'trafficAnalysis.intruder.builtInPayloadListCategories.discovery',
    labelKey: 'trafficAnalysis.intruder.builtInPayloadLists.extensionsLong',
    descriptionKey: 'trafficAnalysis.intruder.builtInPayloadDescriptions.extensionsLong',
    aliases: ['extension', 'suffix', 'ext', '扩展名'],
    tags: ['discovery', 'extension'],
    recommendedAttackTypes: ['clusterBomb', 'pitchfork'],
    recommendedPositionHints: ['ext', 'extension', 'suffix'],
    items: ['.backup', '.config', '.dist', '.example', '.history', '.orig', '.save', '.tar.gz', '.yaml', '.yml'],
  },
  {
    id: 'ports-common',
    categoryKey: 'trafficAnalysis.intruder.builtInPayloadListCategories.discovery',
    labelKey: 'trafficAnalysis.intruder.builtInPayloadLists.commonPorts',
    descriptionKey: 'trafficAnalysis.intruder.builtInPayloadDescriptions.commonPorts',
    aliases: ['port', 'service', '端口'],
    tags: ['discovery', 'port'],
    recommendedAttackTypes: ['sniper', 'pitchfork'],
    recommendedPositionHints: ['port', 'service'],
    items: COMMON_PORTS,
  },
  {
    id: 'api-endpoints-common',
    categoryKey: 'trafficAnalysis.intruder.builtInPayloadListCategories.discovery',
    labelKey: 'trafficAnalysis.intruder.builtInPayloadLists.commonApiEndpoints',
    descriptionKey: 'trafficAnalysis.intruder.builtInPayloadDescriptions.commonApiEndpoints',
    aliases: ['api', 'endpoint', 'route', 'path', '接口', '端点'],
    tags: ['discovery', 'api'],
    recommendedAttackTypes: ['sniper', 'clusterBomb'],
    recommendedPositionHints: ['path', 'route', 'api', 'endpoint', 'url'],
    items: COMMON_API_ENDPOINTS,
  },
  {
    id: 'sensitive-files',
    categoryKey: 'trafficAnalysis.intruder.builtInPayloadListCategories.discovery',
    labelKey: 'trafficAnalysis.intruder.builtInPayloadLists.sensitiveFiles',
    descriptionKey: 'trafficAnalysis.intruder.builtInPayloadDescriptions.sensitiveFiles',
    aliases: ['sensitive', 'secret', 'config', '文件', '敏感'],
    tags: ['discovery', 'sensitive'],
    recommendedAttackTypes: ['sniper', 'clusterBomb'],
    recommendedPositionHints: ['path', 'file', 'filename', 'resource'],
    items: SENSITIVE_FILES,
  },
]
