import { describe, expect, it } from 'vitest'
import { normalizeTrafficPluginRuntimeQueueStatsSnapshot } from './trafficPluginRuntimeQueueTypes'

describe('normalizeTrafficPluginRuntimeQueueStatsSnapshot', () => {
  it('normalizes a full queue stats snapshot', () => {
    const snapshot = normalizeTrafficPluginRuntimeQueueStatsSnapshot({
      activeProbe: {
        kind: 'traffic_active_probe',
        pendingCount: 3,
        queuedCount: 2,
        scheduledCount: 1,
        runningCount: 4,
        recentCount: 10,
        maxQueueDepth: 3,
        activeGlobal: 4,
        activeRuns: 2,
        activePlugins: 1,
        activeHosts: 2,
        hottestHost: 'example.com',
        hottestHostActive: 2,
        cancelledRunCount: 0,
        configuredMaxQueueDepth: 1000,
        configuredMaxGlobalConcurrent: 20,
        configuredMaxConcurrentPerHost: 2,
        configuredMaxConcurrentPerRun: 6,
        configuredMaxConcurrentPerPlugin: 10,
        rejectedTotalCount: 4,
        rejectedCancelledRunCount: 1,
        rejectedQueueLimitCount: 1,
        rejectedRunPendingLimitCount: 1,
        rejectedPluginPendingLimitCount: 1,
        recentWindowTotalCount: 3,
        recentWindowCompletedCount: 2,
        recentWindowFailedCount: 1,
        recentWindowCancelledCount: 0,
        recentWindowAvgQueueWaitMs: 120,
        recentWindowAvgResponseElapsedMs: 340,
      },
      bountyFetch: {
        kind: 'bounty_fetch',
        pendingCount: 0,
        queuedCount: 0,
        scheduledCount: 0,
        runningCount: 0,
        recentCount: 0,
        maxQueueDepth: 0,
        activeGlobal: 0,
        activeRuns: 0,
        activePlugins: 0,
        activeHosts: 0,
        hottestHost: null,
        hottestHostActive: 0,
        cancelledRunCount: 0,
        configuredMaxQueueDepth: 1000,
        configuredMaxGlobalConcurrent: 20,
        configuredMaxConcurrentPerHost: 2,
        configuredMaxConcurrentPerRun: 6,
        configuredMaxConcurrentPerPlugin: 10,
        rejectedTotalCount: 0,
        rejectedCancelledRunCount: 0,
        rejectedQueueLimitCount: 0,
        rejectedRunPendingLimitCount: 0,
        rejectedPluginPendingLimitCount: 0,
        recentWindowTotalCount: 0,
        recentWindowCompletedCount: 0,
        recentWindowFailedCount: 0,
        recentWindowCancelledCount: 0,
        recentWindowAvgQueueWaitMs: 0,
        recentWindowAvgResponseElapsedMs: 0,
      },
      monitorFetch: {
        kind: 'monitor_fetch',
        pendingCount: 0,
        queuedCount: 0,
        scheduledCount: 0,
        runningCount: 0,
        recentCount: 0,
        maxQueueDepth: 0,
        activeGlobal: 0,
        activeRuns: 0,
        activePlugins: 0,
        activeHosts: 0,
        hottestHost: null,
        hottestHostActive: 0,
        cancelledRunCount: 0,
        configuredMaxQueueDepth: 500,
        configuredMaxGlobalConcurrent: 8,
        configuredMaxConcurrentPerHost: 1,
        configuredMaxConcurrentPerRun: 3,
        configuredMaxConcurrentPerPlugin: 4,
        rejectedTotalCount: 0,
        rejectedCancelledRunCount: 0,
        rejectedQueueLimitCount: 0,
        rejectedRunPendingLimitCount: 0,
        rejectedPluginPendingLimitCount: 0,
        recentWindowTotalCount: 0,
        recentWindowCompletedCount: 0,
        recentWindowFailedCount: 0,
        recentWindowCancelledCount: 0,
        recentWindowAvgQueueWaitMs: 0,
        recentWindowAvgResponseElapsedMs: 0,
      },
      agentFetch: {
        kind: 'agent_fetch',
        pendingCount: 0,
        queuedCount: 0,
        scheduledCount: 0,
        runningCount: 0,
        recentCount: 0,
        maxQueueDepth: 0,
        activeGlobal: 0,
        activeRuns: 0,
        activePlugins: 0,
        activeHosts: 0,
        hottestHost: null,
        hottestHostActive: 0,
        cancelledRunCount: 0,
        configuredMaxQueueDepth: 300,
        configuredMaxGlobalConcurrent: 10,
        configuredMaxConcurrentPerHost: 2,
        configuredMaxConcurrentPerRun: 4,
        configuredMaxConcurrentPerPlugin: 6,
        rejectedTotalCount: 0,
        rejectedCancelledRunCount: 0,
        rejectedQueueLimitCount: 0,
        rejectedRunPendingLimitCount: 0,
        rejectedPluginPendingLimitCount: 0,
        recentWindowTotalCount: 0,
        recentWindowCompletedCount: 0,
        recentWindowFailedCount: 0,
        recentWindowCancelledCount: 0,
        recentWindowAvgQueueWaitMs: 0,
        recentWindowAvgResponseElapsedMs: 0,
      },
      pluginTestFetch: {
        kind: 'plugin_test_fetch',
        pendingCount: 0,
        queuedCount: 0,
        scheduledCount: 0,
        runningCount: 0,
        recentCount: 0,
        maxQueueDepth: 0,
        activeGlobal: 0,
        activeRuns: 0,
        activePlugins: 0,
        activeHosts: 0,
        hottestHost: null,
        hottestHostActive: 0,
        cancelledRunCount: 0,
        configuredMaxQueueDepth: 50,
        configuredMaxGlobalConcurrent: 2,
        configuredMaxConcurrentPerHost: 1,
        configuredMaxConcurrentPerRun: 2,
        configuredMaxConcurrentPerPlugin: 2,
        rejectedTotalCount: 0,
        rejectedCancelledRunCount: 0,
        rejectedQueueLimitCount: 0,
        rejectedRunPendingLimitCount: 0,
        rejectedPluginPendingLimitCount: 0,
        recentWindowTotalCount: 0,
        recentWindowCompletedCount: 0,
        recentWindowFailedCount: 0,
        recentWindowCancelledCount: 0,
        recentWindowAvgQueueWaitMs: 0,
        recentWindowAvgResponseElapsedMs: 0,
      },
    })

    expect(snapshot?.activeProbe.pendingCount).toBe(3)
    expect(snapshot?.activeProbe.hottestHost).toBe('example.com')
    expect(snapshot?.activeProbe.rejectedTotalCount).toBe(4)
    expect(snapshot?.activeProbe.recentWindowAvgQueueWaitMs).toBe(120)
    expect(snapshot?.bountyFetch.configuredMaxQueueDepth).toBe(1000)
    expect(snapshot?.pluginTestFetch.kind).toBe('plugin_test_fetch')
  })
})
